spring:
  data:
    mongodb:
      host: 192.168.31.249
      port: 10000

app:
  port: 8080
  redis-uri: redis://localhost:6379
  login-html-uri: /login.html
  confirm-html-uri: /confirm.html
  token:
    salt: 847b28a6-89bf-41be-96b8-f0c1a94a3353
  refresh-token:
    salt: 91445f93-8744-4bfa-96f4-0c944b7686c1
  weixin:
    apps:
      # weixin pc
      pc:
        app-id: wx8120ce5a486794d7
        app-secret: 666e078f9804095ec04d72d1ee540714
      # weixin app
      app:
        app-id: wxc3074c6fb652a29a
        app-secret: e49fe2063ae15a08d073f4f96189af93
      # weixin h5
      h5:
        app-id: wx27a01ce6c6c3e0e8
        app-secret: 6d8d88703396a68d6dff50caef7c0491
