#%RAML 1.0
title: Uia API
version: v1
baseUri: '{uri}/{version}'
baseUriParameters:
  uri:
    type: string
    default: 'http://localhost:8080/api'
/oauth:
  /token:
    post:
      body:
        application/x-www-form-urlencoded:
          properties:
            grant_type:
              type: string
              enum: ["password"]
            client_id:
              type: string
              required: false
            client_secret:
              type: string
              required: false
            username:
              type: string
              required: false
            password:
              type: string
              required: false
            scope:
              type: string
              required: false
      responses:
        200:
          body:
            application/json:
              example: |
                {
                  "message" : "Hello World"
                }
        400:
          body:
            application/json:
