#%RAML 1.0
title: Uia API
version: v1
baseUri: http://localhost:8080/api/{version}

/oauth/token:
  post:
    body:
      application/x-www-form-urlencoded:
        properties:
          grant_type:
            type: string
            description: 值为 password
          client_id:
            type: string
          client_secret: string
          username: string
          password: string
          scope:
            type: string
            required: false
            description: 授权作用域
    responses:
      200:
        body:
          application/json:
            example: |
              {
                "access_token": "AxJrX4EoKjNnHxUD3KZLqkQjwByNn0VQ",
                "refresh_token":"6PvjOW2JaXkpFJCm7vO31eM9KYVx4R7l",
                "expires_in":7000
              }
      401:
        body:
          application/json:
            examples:
              invalid_client: |
                {
                  "error": "invalid_client",
                  "error_description": "未发现指定 client_id 客户端记录"
                }
              invalid_grant: |
                {
                  "error": "invalid_grant",
                  "error_description": "未发现指定 email 的用户"
                }
